# Extra detekt config to change the default.
naming:
  FunctionNaming:
    ignoreAnnotated: [ 'DevicePreviews', 'Composable' ]

style:
  UnusedPrivateMember:
    ignoreAnnotated: [ 'DevicePreviews' ]
  MaxLineLength:
    excludes: [ "**/test/**","**/androidTest/**" ]
  MagicNumber:
    ignorePropertyDeclaration: true
    excludes: [ "**/test/**","**/androidTest/**","**/compose/**" ]

TwitterCompose:
  CompositionLocalAllowlist:
    active: true
  CompositionLocalNaming:
    active: true
  ContentEmitterReturningValues:
    active: true
    # You can optionally add your own composables here
    # contentEmitters: MyComposable,MyOtherComposable
  ModifierComposable:
    active: true
  ModifierMissing:
    active: true
  ModifierReused:
    active: true
  ModifierWithoutDefault:
    active: true
  MultipleEmitters:
    active: true
    # You can optionally add your own composables here
    # contentEmitters: MyComposable,MyOtherComposable
  MutableParams:
    active: true
  ComposableNaming:
    active: true
    # You can optionally disable the checks in this rule for regex matches against the composable name (e.g. molecule presenters)
    # allowedComposableFunctionNames: .*Presenter,.*MoleculePresenter
  ComposableParamOrder:
    active: true
  PreviewNaming:
    active: true
  PreviewPublic:
    active: true
    # You can optionally disable that only previews with @PreviewParameter are flagged
    # previewPublicOnlyIfParams: false
  RememberMissing:
    active: true
  UnstableCollections:
    active: false
  ViewModelForwarding:
    active: true
  ViewModelInjection:
    active: true
