name: Pull Request CI

on:
  pull_request:
    # push: I'm the only one working on the project.
    branches:
      - main
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Check spotless
        run: ./gradlew --init-script gradle/init.gradle.kts spotlessCheck --no-configuration-cache

      - name: Check lint
        run: ./gradlew lintDebug

      - name: Build debug build type
        run: ./gradlew assembleDebug

      - name: Run debug unit tests and create jacoco report
        run: ./gradlew testDebugUnitTest

      - name: Verify jacoco code coverage
        run: ./gradlew jacocoCoverageVerification

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs
          path: app/build/outputs

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: app/build/reports
